Traceback (most recent call last):
  File "paths_constraints_main.py", line 5, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/__init__.py", line 22, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/utils/__init__.py", line 5, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/utils/enums_conv.py", line 6, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/protos/__init__.py", line 10, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/protos/primitives_pb2.py", line 5, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 753, in <module>
MemoryError
