WARNING | 2021-11-30 15:54:54,511 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_log_to_stderr
WARNING | 2021-11-30 15:54:54,512 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: dico_markup_type
WARNING | 2021-11-30 15:54:54,512 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_error_count
WARNING | 2021-11-30 15:54:54,512 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: dico_invocation_name
WARNING | 2021-11-30 15:54:54,512 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_print_diag_fun
WARNING | 2021-11-30 15:54:54,513 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: dico_program_name
WARNING | 2021-11-30 15:54:54,513 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_parser_options
WARNING | 2021-11-30 15:54:54,513 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_preprocessor
WARNING | 2021-11-30 15:54:54,513 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: grecs_default_port
WARNING | 2021-11-30 15:54:54,513 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: dico_argcv_quoting_style
WARNING | 2021-11-30 15:54:54,525 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
ERROR   | 2021-11-30 16:27:23,539 | root     | list index out of range
ERROR   | 2021-11-30 16:27:23,539 | root     | got an error while analyzing dicod_database_match
ERROR   | 2021-11-30 16:28:01,477 | root     | argument 3: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object
ERROR   | 2021-11-30 16:28:01,477 | root     | got an error while analyzing find_key
ERROR   | 2021-11-30 16:50:07,935 | root     | list index out of range
ERROR   | 2021-11-30 16:50:07,935 | root     | got an error while analyzing dicod_server
ERROR   | 2021-11-30 17:43:45,670 | root     | 
ERROR   | 2021-11-30 17:43:45,670 | root     | got an error while analyzing gl_des_ecb_crypt
ERROR   | 2021-11-30 18:23:45,645 | root     | 
ERROR   | 2021-11-30 18:23:45,646 | root     | got an error while analyzing gl_3des_ecb_crypt
ERROR   | 2021-11-30 19:56:13,410 | root     | b'out of memory'
ERROR   | 2021-11-30 19:56:13,411 | root     | got an error while analyzing locale_charset
